name: Polypheny-DB Adapter Matrix CI

on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/ipython-polypheny
        name: Build & Publish To PyPI
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-python@v4
                with:
                    python-version: '3.10'
            -   name: Build Package
                run: |
                    python -m pip install --upgrade build
                    python -m build
            # add github release
            -   name: Publish package distributions to PyPI
                uses: pypa/gh-action-pypi-publish@release/v1
                with:
                    packages-dir: dist/
                    password: ${{ secrets.PYPI_API_TOKEN }}
                    #repository_url: https://pypi.org/legacy/