name: Polypheny-DB Adapter Matrix CI

on:
    push:
        branches:
            - main
    issues: # for debugging
        types:
            - opened
jobs:
    build:
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/<your-pypi-project-name>
        permissions:
            id-token: write
        name: Build & Publish To PyPI
        steps:
            -   name: Setup Python
            -   uses: actions/setup-python@v4
                with:
                    python-version: '3.10'
            -   name: Checkout Repository
            -   uses: actions/checkout@v3
            -   name: Build Package
                run: |
                    python -m pip install --upgrade build
                    python -m build
            # add github release
            -   name: Publish package distributions to PyPI
            -   uses: pypa/gh-action-pypi-publish@release/v1
                with:
                    packages-dir: dist/
                    password: ${{ secrets.TEST_PYPI_API_TOKEN }}
                    repository_url: https://test.pypi.org/legacy/